# Generated by Django 6.1 on 2026-09-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("slug", models.CharField(blank=True, max_length=200, null=True, verbose_name="slug")),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/", verbose_name="Превью (изображение)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_published", models.BooleanField(default=True, verbose_name="Признак публикации")),
                ("views_count", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "блоговая запись",
                "verbose_name_plural": "Блоговые записи",
                "ordering": ["-created_at"],
            },
        ),
    ]
