# Generated by Django 6.1 on 2026-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
            ],
            options={
                "verbose_name": "контактные данные",
                "verbose_name_plural": "Контактные данные",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "категорию", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"], "verbose_name": "товар", "verbose_name_plural": "Товары"},
        ),
    ]
